const starterAssets = (plant = 1, substation = 1, storage = 0) => ({
  plant,
  substation,
  storage,
});

const BASE_TOWNS = [
    {
      id: "capital",
      name: "Capital Metro",
      x: 1040,
      y: 640,
      radius: 64,
      districtType: "Urban Core",
      terrain: "plains",
      climate: "temperate",
      baseDemand: 95,
      population: 120,
      growthRate: 0.6,
      starterAssets: starterAssets(2, 2, 1),
      strategicValue: "National dispatch and policy center",
    },
    {
      id: "north_industry",
      name: "North Industrial Spine",
      x: 1060,
      y: 290,
      radius: 58,
      districtType: "Industrial Belt",
      terrain: "mountains",
      climate: "cold",
      baseDemand: 80,
      population: 70,
      growthRate: 0.9,
      starterAssets: starterAssets(1, 1, 0),
      strategicValue: "High throughput and volatile demand",
    },
    {
      id: "west_hydro",
      name: "West Hydro Town",
      x: 620,
      y: 560,
      radius: 56,
      districtType: "Rural Cluster",
      terrain: "river",
      climate: "temperate",
      baseDemand: 54,
      population: 45,
      growthRate: 0.45,
      starterAssets: starterAssets(1, 1, 1),
      strategicValue: "Reliable clean generation potential",
    },
    {
      id: "east_coast",
      name: "East Coast Port",
      x: 1550,
      y: 610,
      radius: 58,
      districtType: "Coastal Corridor",
      terrain: "coast",
      climate: "warm",
      baseDemand: 72,
      population: 62,
      growthRate: 0.7,
      starterAssets: starterAssets(1, 1, 0),
      strategicValue: "Trade demand with storm vulnerability",
    },
    {
      id: "south_farms",
      name: "South Agricultural Town",
      x: 980,
      y: 1030,
      radius: 56,
      districtType: "Rural Cluster",
      terrain: "plains",
      climate: "warm",
      baseDemand: 48,
      population: 40,
      growthRate: 0.4,
      starterAssets: starterAssets(1, 1, 0),
      strategicValue: "Wide low-density service coverage",
    },
    {
      id: "delta_port",
      name: "Delta Port",
      x: 1340,
      y: 1090,
      radius: 54,
      districtType: "Coastal Corridor",
      terrain: "coast",
      climate: "warm",
      baseDemand: 60,
      population: 52,
      growthRate: 0.55,
      starterAssets: starterAssets(1, 1, 0),
      strategicValue: "Economic bonus when stabilized",
    },
    {
      id: "central_highlands",
      name: "Central Highlands",
      x: 760,
      y: 820,
      radius: 56,
      districtType: "Urban Core",
      terrain: "mountains",
      climate: "cold",
      baseDemand: 66,
      population: 58,
      growthRate: 0.5,
      starterAssets: starterAssets(1, 1, 0),
      strategicValue: "Expensive terrain, critical interconnect",
    },
    {
      id: "frontier_belt",
      name: "Frontier Town",
      x: 1710,
      y: 310,
      radius: 60,
      districtType: "Urban Core",
      terrain: "plains",
      climate: "cold",
      baseDemand: 70,
      population: 55,
      growthRate: 1.0,
      starterAssets: starterAssets(0, 1, 0),
      strategicValue: "Late-run growth pressure and scoring upside",
    },
];

export const BASE_MAP = {
  id: "national-grid-v1",
  name: "National Grid Core",
  width: 2200,
  height: 1400,
  towns: BASE_TOWNS,
  regions: BASE_TOWNS,
  links: [],
};

export const STANDARD_PRESETS = [
  {
    id: "standard",
    label: "Standard",
    description: "Leaderboard-eligible baseline conditions.",
    demandGrowthMultiplier: 1,
    eventIntensity: 1,
    seasonalProfile: "mixed",
    climateIntensity: 1,
    infraCostMultiplier: 1,
    failureStrictness: 1,
    populationMode: "on",
    townEmergenceMode: "normal",
    substationRadiusProfile: "standard",
    lineMaintenanceProfile: "standard",
    routingComplexity: "Moderate",
    budget: 900,
    runTargetMinutes: 18,
    leaderboardEligible: true,
  },
  {
    id: "hard",
    label: "Hard",
    description: "Higher pressure and tighter economy.",
    demandGrowthMultiplier: 1.2,
    eventIntensity: 1.25,
    seasonalProfile: "mixed",
    climateIntensity: 1.25,
    infraCostMultiplier: 1.15,
    failureStrictness: 1.12,
    populationMode: "on",
    townEmergenceMode: "normal",
    substationRadiusProfile: "tight",
    lineMaintenanceProfile: "high",
    routingComplexity: "Intense",
    budget: 860,
    runTargetMinutes: 18,
    leaderboardEligible: true,
  },
  {
    id: "brutal",
    label: "Brutal",
    description: "High volatility and strict collapse thresholds.",
    demandGrowthMultiplier: 1.35,
    eventIntensity: 1.45,
    seasonalProfile: "mixed",
    climateIntensity: 1.35,
    infraCostMultiplier: 1.25,
    failureStrictness: 1.25,
    populationMode: "on",
    townEmergenceMode: "high",
    substationRadiusProfile: "tight",
    lineMaintenanceProfile: "high",
    routingComplexity: "Intense",
    budget: 820,
    runTargetMinutes: 20,
    leaderboardEligible: true,
  },
];

export const CUSTOM_OPTIONS = {
  seasonalProfile: ["neutral", "winter-peak", "summer-peak", "mixed"],
  populationMode: ["off", "normal", "high"],
  climateIntensity: ["low", "normal", "high"],
  townEmergenceIntensity: ["off", "limited", "normal", "high"],
  substationRadiusProfile: ["wide", "standard", "tight"],
  lineMaintenanceProfile: ["low", "standard", "high"],
  eventIntensity: ["low", "normal", "high"],
  failureStrictness: ["lenient", "standard", "strict"],
  runTargetMinutes: [12, 15, 18, 24],
};

export const CUSTOM_PRESETS = [
  {
    id: "training",
    label: "Training",
    demandGrowthMultiplier: 0.8,
    eventIntensity: 0.7,
    seasonalProfile: "neutral",
    climateIntensity: 0.8,
    infraCostMultiplier: 0.9,
    failureStrictness: 0.8,
    populationMode: "off",
    townEmergenceIntensity: "off",
    substationRadiusProfile: "wide",
    lineMaintenanceProfile: "low",
    budget: 980,
    runTargetMinutes: 15,
    leaderboardEligible: false,
  },
  {
    id: "standard",
    label: "Custom Standard",
    demandGrowthMultiplier: 1,
    eventIntensity: 1,
    seasonalProfile: "mixed",
    climateIntensity: 1,
    infraCostMultiplier: 1,
    failureStrictness: 1,
    populationMode: "normal",
    townEmergenceIntensity: "normal",
    substationRadiusProfile: "standard",
    lineMaintenanceProfile: "standard",
    budget: 900,
    runTargetMinutes: 18,
    leaderboardEligible: true,
  },
];

export const SEASON_ORDER = ["winter", "spring", "summer", "autumn"];

export const CLIMATE_MULTIPLIERS = {
  winter: { cold: 1.28, temperate: 1.1, warm: 0.94 },
  spring: { cold: 1.02, temperate: 1.0, warm: 0.98 },
  summer: { cold: 0.95, temperate: 1.08, warm: 1.3 },
  autumn: { cold: 1.08, temperate: 1.0, warm: 1.02 },
  neutral: { cold: 1, temperate: 1, warm: 1 },
};

export const TERRAIN_COST_MULTIPLIERS = {
  plains: 1,
  mountains: 1.35,
  river: 1.18,
  coast: 1.15,
};

export const ASSET_RULES = {
  plant: {
    label: "Generation Plant",
    cost: 135,
    refundRatio: 0.5,
    generation: 60,
    operatingCostPerSecond: 1.9,
    reliabilityBonus: 0.2,
  },
  substation: {
    label: "Substation",
    cost: 92,
    refundRatio: 0.45,
    generation: 0,
    operatingCostPerSecond: 1.0,
    reliabilityBonus: 0.45,
  },
  storage: {
    label: "Storage",
    cost: 78,
    refundRatio: 0.4,
    generation: 20,
    operatingCostPerSecond: 0.65,
    reliabilityBonus: 0.35,
  },
};

export const CAMPAIGN_MISSIONS = [
  {
    id: "m01-cold-start",
    codename: "Cold Start",
    arc: "Founding",
    premise: "Bootstrap power to capital and one rural corridor.",
    difficulty: "Easy",
    mapScale: "Small",
    routingComplexity: "Simple",
    populationMode: "off",
    seasonalMode: "off",
    townEmergenceMode: "off",
    startingBudget: 860,
    objective: {
      type: "stability",
      description: "Keep reliability above 70 while stably serving at least 4 towns for 4 minutes.",
      targetDurationSec: 240,
      reliabilityFloor: 70,
      requiredStableTowns: 4,
    },
  },
  {
    id: "m02-rolling-summer",
    codename: "Rolling Summer",
    arc: "Founding",
    premise: "Survive early cooling demand spikes.",
    difficulty: "Easy",
    mapScale: "Small",
    routingComplexity: "Simple",
    populationMode: "off",
    seasonalMode: "on",
    townEmergenceMode: "off",
    startingBudget: 840,
    objective: {
      type: "stability",
      description: "Maintain reliability above 68 while stably serving at least 4 towns for 5 minutes.",
      targetDurationSec: 300,
      reliabilityFloor: 68,
      requiredStableTowns: 4,
    },
  },
  {
    id: "m03-fuel-shock",
    codename: "Fuel Shock",
    arc: "Founding",
    premise: "Cost surges punish overbuilding.",
    difficulty: "Normal",
    mapScale: "Small",
    routingComplexity: "Simple",
    populationMode: "off",
    seasonalMode: "on",
    townEmergenceMode: "off",
    startingBudget: 820,
    objective: {
      type: "economy",
      description: "Finish 5 minutes above 120 budget while keeping 5 towns stably served.",
      targetDurationSec: 300,
      reliabilityFloor: 64,
      budgetFloor: 120,
      requiredStableTowns: 5,
    },
  },
  {
    id: "m04-coastal-storm",
    codename: "Coastal Storm",
    arc: "Founding",
    premise: "Restore coastal service after repeated disruptions.",
    difficulty: "Normal",
    mapScale: "Small",
    routingComplexity: "Moderate",
    populationMode: "normal",
    seasonalMode: "on",
    townEmergenceMode: "limited",
    startingBudget: 820,
    objective: {
      type: "stability",
      description: "Stabilize service across at least 5 towns for 6 minutes.",
      targetDurationSec: 360,
      reliabilityFloor: 66,
      requiredStableTowns: 5,
    },
  },
  {
    id: "m05-industrial-push",
    codename: "Industrial Push",
    arc: "Expansion",
    premise: "Growth pressure comes online in the north corridor.",
    difficulty: "Normal",
    mapScale: "Medium",
    routingComplexity: "Moderate",
    populationMode: "normal",
    seasonalMode: "on",
    townEmergenceMode: "limited",
    startingBudget: 900,
    objective: {
      type: "growth",
      description: "Maintain reliability above 70 while stably serving at least 6 towns for 7 minutes.",
      targetDurationSec: 420,
      reliabilityFloor: 70,
      requiredStableTowns: 6,
    },
  },
  {
    id: "m06-dry-season",
    codename: "Dry Season",
    arc: "Expansion",
    premise: "Hydro output dips while coverage planning gets tighter.",
    difficulty: "Normal",
    mapScale: "Medium",
    routingComplexity: "Moderate",
    populationMode: "normal",
    seasonalMode: "on",
    townEmergenceMode: "normal",
    startingBudget: 900,
    objective: {
      type: "stability",
      description: "Hold reliability above 69 while keeping 6 towns in stable coverage.",
      targetDurationSec: 420,
      reliabilityFloor: 69,
      requiredStableTowns: 6,
    },
  },
  {
    id: "m07-night-surge",
    codename: "Night Surge",
    arc: "Expansion",
    premise: "Steep demand oscillation tests reroute decisions.",
    difficulty: "Hard",
    mapScale: "Medium",
    routingComplexity: "Intense",
    populationMode: "normal",
    seasonalMode: "on",
    townEmergenceMode: "normal",
    startingBudget: 890,
    objective: {
      type: "stability",
      description: "Survive 7 minutes with reliability above 67 and 6 towns stably served.",
      targetDurationSec: 420,
      reliabilityFloor: 67,
      requiredStableTowns: 6,
    },
  },
  {
    id: "m08-election-quarter",
    codename: "Election Quarter",
    arc: "Expansion",
    premise: "Avoid lawsuit cascades while demand rises.",
    difficulty: "Hard",
    mapScale: "Medium",
    routingComplexity: "Intense",
    populationMode: "normal",
    seasonalMode: "on",
    townEmergenceMode: "normal",
    startingBudget: 880,
    objective: {
      type: "trust",
      description: "Finish 8 minutes with no more than 2 lawsuits.",
      targetDurationSec: 480,
      reliabilityFloor: 66,
      maxLawsuits: 2,
      requiredStableTowns: 7,
    },
  },
  {
    id: "m09-grid-retrofit",
    codename: "Grid Retrofit",
    arc: "Transition",
    premise: "Retool assets under tight capital.",
    difficulty: "Hard",
    mapScale: "Large",
    routingComplexity: "Intense",
    populationMode: "high",
    seasonalMode: "on",
    townEmergenceMode: "normal",
    startingBudget: 910,
    objective: {
      type: "economy",
      description: "End 8 minutes above 80 budget while keeping 7 towns stably served.",
      targetDurationSec: 480,
      reliabilityFloor: 68,
      budgetFloor: 80,
      requiredStableTowns: 7,
    },
  },
  {
    id: "m10-cross-country-link",
    codename: "Cross-Country Link",
    arc: "Transition",
    premise: "Establish and hold a stable long-haul backbone.",
    difficulty: "Hard",
    mapScale: "Large",
    routingComplexity: "Intense",
    populationMode: "high",
    seasonalMode: "on",
    townEmergenceMode: "normal",
    startingBudget: 930,
    objective: {
      type: "backbone",
      description: "Maintain 7 stably served towns and 70 reliability for 8 minutes.",
      targetDurationSec: 480,
      reliabilityFloor: 70,
      requiredStableTowns: 7,
    },
  },
  {
    id: "m11-green-mandate",
    codename: "Green Mandate",
    arc: "Transition",
    premise: "Limited generation options with seasonal swings.",
    difficulty: "Hard",
    mapScale: "Large",
    routingComplexity: "Intense",
    populationMode: "high",
    seasonalMode: "on",
    townEmergenceMode: "normal",
    startingBudget: 940,
    objective: {
      type: "stability",
      description: "Survive 9 minutes above 71 reliability while stabilizing 8 towns.",
      targetDurationSec: 540,
      reliabilityFloor: 71,
      requiredStableTowns: 8,
    },
  },
  {
    id: "m12-national-peak",
    codename: "National Peak",
    arc: "Transition",
    premise: "Final full-map management scenario.",
    difficulty: "Expert",
    mapScale: "Large",
    routingComplexity: "Intense",
    populationMode: "high",
    seasonalMode: "on",
    townEmergenceMode: "normal",
    startingBudget: 960,
    objective: {
      type: "full-map",
      description: "Stabilize all 8 core towns for 10 minutes.",
      targetDurationSec: 600,
      reliabilityFloor: 72,
      requiredStableTowns: 8,
    },
  },
];

export const ALERT_LEVELS = {
  advisory: { label: "Advisory", color: "#4ea2ff", icon: "i" },
  warning: { label: "Warning", color: "#f7b955", icon: "!" },
  critical: { label: "Critical", color: "#ff6262", icon: "!!" },
};

export const NEWS_BLURBS = [
  "Cabinet brief: maintenance backlog is under review.",
  "National bulletin: urban demand remains elevated.",
  "Policy desk: lawmakers request outage risk reduction.",
  "Regional dispatch: transmission utilization spikes in the north.",
  "Treasury signal: capital discipline remains a top priority.",
  "Public sentiment: stable service improves confidence.",
];

export const STORAGE_KEYS = {
  records: "stg_records_v1",
  settings: "stg_settings_v1",
  suspendedRun: "stg_suspended_run_v1",
  campaignProgress: "stg_campaign_progress_v1",
  devMode: "stg_dev_mode_v1",
  tutorialCompleted: "stg_tutorial_completed_v1",
};

export const DEFAULT_SETTINGS = {
  uiScale: "normal",
  highContrast: false,
  reducedMotion: false,
};
